# example = "The framers of our Constitution wanted us to live in a nation that upholds freedom of thought and expression and where there is justice for all. For that to happen we need a judicial system that is free from all influences and acts impartially. To maintain the independence of the judiciary certain features were created for those serving in the judicial system:To ensure that judges of the Supreme Court and High Courts do not suffer from insecurity of service, that is, loss of job and are not put under any pressure to deliver judgements in favour of the government, the Constitution clearly states that while the President appoints them, neither he/she nor any other person can remove them from office. ‘This gives them ease to discharge their duties without any fear of external pressure or loss of their jobs.‘The salary and perks of the judiciary are charged to the Consolidated Fund of India and neither the Parliament nor the Executive has any control over it. This is why the judges can deliver judgements against the bills passed by the Parliament without any fear of removal.Their personal security and that of their family is the responsibility of the State. This allows them to handle criminal cases dealing with ruthless criminals without fear of any repercussions on themselves or their families. They can declare their decisions in court without fear of censure and criticism in the press."
# print(get_keywords(example))
from final_files.baseline.evaluation import keywords_lost
from final_files.util import sentence_tokenizer

example = "The framers of our Constitution wanted us to live in a nation that upholds freedom of thought and expression and where there is justice for all. For that to happen we need a judicial system that is free from all influences and acts impartially. To maintain the independence of the judiciary certain features were created for those serving in the judicial system:To ensure that judges of the Supreme Court and High Courts do not suffer from insecurity of service, that is, loss of job and are not put under any pressure to deliver judgements in favour of the government, the Constitution clearly states that while the President appoints them, neither he/she nor any other person can remove them from office. ‘This gives them ease to discharge their duties without any fear of external pressure or loss of their jobs.‘The salary and perks of the judiciary are charged to the Consolidated Fund of India and neither the Parliament nor the Executive has any control over it. This is why the judges can deliver judgements against the bills passed by the Parliament without any fear of removal.Their personal security and that of their family is the responsibility of the State. This allows them to handle criminal cases dealing with ruthless criminals without fear of any repercussions on themselves or their families. They can declare their decisions in court without fear of censure and criticism in the press."
xlmsummary = "the framers of our constitution wanted us to live in a nation that upholds freedom of thought and expression and where there is justice for all. for that to happen we need a judicial system that is free from all influences and acts impartially. to maintain the independence of the judiciary certain features were created for those serving in the judicial system : to ensure that judges of the supreme court and high courts do not suffer from insecurity of service, that is, loss of job and are not put under any pressure to deliver judgements in favour of the government, the constitution clearly states that while the president appoints them, neither he / she nor any other person can remove them from office.'this gives them ease to discharge their duties without any fear of external pressure or loss of their jobs.'the salary and perks of the judiciary are charged to the consolidated fund of india and neither the parliament nor the executive has any control over it. this is why the judges can deliver judgements and"

print(keywords_lost(example, xlmsummary))
def pre_process_text(text):
    new_lines_removed = text.replace('\n', '')
    # Make sure sentences are separated by a space
    sentences = sentence_tokenizer(new_lines_removed)

    return " ".join(sentences)